import "@/src/styles/globals.css";
import type { Metadata } from "next";
import { fonts } from "@/src/lib/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`mx-auto max-w-[1920px] relative ${fonts.className}`}>
        {children}
      </body>
    </html>
  );
}
